### ISSUE TITLE
Troubleshooting Analysis of Heterogenous Patient Data (such as TCGA)

### ISSUE THREAD

**Issue by cwarden45** [cwarden45/COHCAP#4]
I am transferring part of a discussion from SourceForge to GitHub.

So, I hope it is OK that I am copying the following content, and I will post responses as an individual (truely myself)

## Copied (and Slightly Modified) Content

[The] Sample file has only 2 groups i,e primary and solid tisssue normal.

Now the code is :

```
dir = "/Users/dkaur/Desktop/HNSC/COHCAP/Files"
beta.file = file.path(dir,"S3.txt")
sample.file = file.path(dir,"Sample_HNSC.txt")
expression.file = file.path(dir,"expression-Average_by_Island.txt")
project.folder = "/Users/dkaur/Desktop/HNSC/"
project.name = "HNSC-SUB"

#code chunk number 2: annotation
beta.table = COHCAP.annotate(beta.file, project.name, project.folder,
platform="450k-UCSC")

#code chunk number 3: site
filtered.sites = COHCAP.site(sample.file, beta.table, project.name,
project.folder, ref="Solid Tissue Normal")

#code chunk number 4: island
island.list = COHCAP.avg.by.island(sample.file, filtered.sites, beta.table,
project.name, project.folder, ref="Solid Tissue Normal")

#code chunk number 5: integrate
COHCAP.integrate.avg.by.island(island.list, project.name, project.folder,
expression.file, sample.file)
```

But i am getting this for my subsample :

```
"Reading Sample Description File...."
[1] 21 580
[1] 21 578
[1] "Group: Primary.Tumor" "Group: Solid.Tissue.Normal"
[1] "Checking CpG Site Stats Table"
[1] 0 10
[1] 0 10
[1] 0
[1] "Average CpG Sites per CpG Island"
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 0 8
[1] 0 8
[1] "There are 0 differentially methylated islands"
[1] 0 580
[1] 0 580
```

This on my full data :

```
1] 375044 581
[1] 374979 5
[1] 374979 585
[1] "Reading Sample Description File...."
[1] 374979 580
[1] 374979 578
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 374979 5
[1] 374979 10
[1] 374979 10
[1] 0 10
[1] 0 10
[1] "Reading Sample Description File...."
[1] 374979 580
[1] 374979 578
[1] "Group: Primary.Tumor" "Group: Solid.Tissue.Normal"
[1] "Checking CpG Site Stats Table"
[1] 0 10
[1] 0 10
[1] 0
[1] "Average CpG Sites per CpG Island"
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 0 8
[1] 0 8
[1] "There are 0 differentially methylated islands"
[1] 0 580
[1] 0 580
[1] 0 580
[1] 0 8
[1] 0
```

So it seems like there is no differentially methylated sites, which is bit weird. Can you suggest any change in the cutoff values?

**Comment by cwarden45** [comment]
**First**, even if I may not be able to run my troubleshooting on the **full beta file**, thank you very much for showing the results when using the full number of CpG Sites.

For example, as you perhaps guessed, the ability to create a truncated demo dataset was dependent upon knowing which sites were **_already_** part of CpG Islands that were differentially methylated.

**Second**, I apologize that I have to provide support for COHCAP usage after working on other responsibilities.

So, I have not taken time for consideration of your specific data, and I have mentioned that there may already be limitations in what I can notice with the truncated dataset.

Nevertheless, these are some **general** recommendations:

- As mentioned briefly an earlier SourceForge response, there is discussion about **changing parameters** [here](https://sourceforge.net/p/cohcap/discussion/bioconductor/thread/c8ad3039/) and [here](https://sourceforge.net/p/cohcap/discussion/bioconductor/thread/95bf9f25/) and [here](https://sourceforge.net/p/cohcap/discussion/bioconductor/thread/d1fbce48/).  I am not sure what is best for this specific dataset, but one possible example would be to use `methyl.cutoff = 0.3`.  I am not sure if you start to get too many results; however, if it helps with checking for the lack of some other formatting issue you can also try something like `methyl.cutoff=0 unmethyl.cutoff=1 delta.beta.cutoff=0.2` (which disables the methylated and unmethylated thresholds, and only uses a delta-beta threshold for differential methylation).
- I don't exactly have the same amount of supporting data as for [RNA-Seq gene expression analysis](https://cdwscience.blogspot.com/2019/11/requiring-at-least-some-methods-testing.html).  However, [one of the comments on the COHCAP paper](https://academic.oup.com/nar/article/41/11/e117/2411160?login=true#usercomments) mentions some limitations in having more fully automated analysis.  In other words, before any publication, you should perform **additional critical assessment**.  This includes (but is not limited to) experimental validation.  In some sense, I think posting questions instead of publishing a list of 0 differentially methylated sites or regions already counts as some additional critical assessment.  However, in general for all users, **please be aware that feedback in this forum is not sufficient to be 100% sure that you have a particular strategy that should be used in a publication**.  Nevertheless, you are welcome to acknowledge support provided this way.

There are also other options available for Illumina DNA Methylation Array data, and I strongly recommend testing multiple methods on your data prior to publication.  Details of this critical assessment can often be described in Supplemental Materials.  For example, for EPIC analysis I have a [template](https://github.com/cwarden45/DNAmethylation_templates/tree/master/EPIC_workflow) that describes some additional methods (although mostly using [minfi](https://bioconductor.org/packages/release/bioc/html/minfi.html) for upstream processing, _if you have the raw .idat files_).  Unlike the RRBS template, I am not exactly running something different for differential methylation.  However, one of the SourceForge links mentions using [bumphunter](https://bioconductor.org/packages/release/bioc/html/bumphunter.html), the COHCAP paper itself mentions that running analysis with both COHCAP and [IMA](https://rforge.net/IMA/) can provide complementary results, and the [Protocol Exchange](https://protocolexchange.researchsquare.com/article/nprot-2965/v1) listing (for the Bioconductor version) shows some benchmarks with other methods like [RnBeads](https://rnbeads.org/) (with the cell line comparison from the publication).

I hope that this might help.

Best Wishes,
Charles

**Comment by Dilraj-kaur** [comment]
Hi Charles
Thank you so much for your response, i tried to change the parameter in 


filtered.sites <- COHCAP.site(sample.file, beta.table, project.name, project.folder,
                              ref="Solid Tissue Normal", methyl.cutoff=0.3, unmethyl.cutoff=1, delta.beta.cutoff=0.2, pvalue.cutoff=0.05)


island.list <- COHCAP.avg.by.island(sample.file, filtered.sites, beta.table, project.name, project.folder,
                                         ref="Solid Tissue Normal", methyl.cutoff=0, unmethyl.cutoff=1, delta.beta.cutoff=0.2, pvalue.cutoff=0.05)


and i am getting theis results:

 island.list <- COHCAP.avg.by.island(sample.file, filtered.sites, beta.table, project.name, project.folder,
+                                          ref="Solid Tissue Normal", methyl.cutoff=0, unmethyl.cutoff=1, delta.beta.cutoff=0.2, pvalue.cutoff=0.05)
[1] "Reading Sample Description File...."
[1]  21 580
[1]  21 578
[1] "Group: Primary.Tumor"       "Group: Solid.Tissue.Normal"
[1] "Checking CpG Site Stats Table"
[1]  0 10
[1]  0 10
[1] 0
[1] "Average CpG Sites per CpG Island"
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 0 8
[1] "unmethyl.cutoff > methyl.cutoff ..."
[1] "so, delta-beta decides which group should be subject to which cutoff"
[1] 0 8
[1] "There are 0 differentially methylated islands"
[1]   0 580
[1]   0 580


Thanks
Dilraj Kaur

**Comment by cwarden45** [comment]
Hi Dilraj,

Thank you very much for following up on GitHub.

**First**, I would like to re-emphasize the troubleshooting assistance that I provide will _**not**_ necessarily provide you with exactly what you should publish.  Based upon your GitHub profile, I don't think this should be an issue.  However, I want to make sure that is extra clear for yourself and others.

**Second**, I agree those results look unexpected.  Troubleshooting running the code is exactly the purpose of the forum.  So, what I can do is use the **truncated dataset** and test using parameters that I think are most likely **too lenient** for publication.

I see that you used the parameter `pvalue.cutoff=0.05`, so perhaps you already had a similar idea.  However, you would then need to change the `fdr.cutoff` parameter

Nevertheless, here is the output if using the truncated dataset (with `fdr.cutoff=1`, using the uploaded `test_COHCAP-GitHub-test1.R` file):

```
Loading required package: WriteXLS
Loading required package: COHCAPanno
Loading required package: RColorBrewer
Loading required package: gplots

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

[1]  21 581
[1] 21  5
[1]  21 585
[1] "Reading Sample Description File...."
[1]  21 580
[1]  21 578
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 21  5
[1] 21 10

[1] 21 10
[1] "unmethyl.cutoff > methyl.cutoff ..."
[1] "so, delta-beta decides which group should be subject to which cutoff"
[1]  0 10
[1]  0 10
[1]  0 10
[1]  0 10
Warning messages:
1: package ‘RColorBrewer’ was built under R version 4.1.3 
2: package ‘gplots’ was built under R version 4.1.3 

```

I am not sure how much the **third section/point** might matter.  However, if I try to stick with the same comparison and the idea of how to check the code is working, I will now try using `delta.beta.cutoff=0.01,pvalue.cutoff=1, fdr.cutoff=1` (with the uploaded `test_COHCAP-GitHub-test2.R` file):

```
Loading required package: WriteXLS
Loading required package: COHCAPanno
Loading required package: RColorBrewer
Loading required package: gplots

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

[1]  21 581
[1] 21  5
[1]  21 585
[1] "Reading Sample Description File...."
[1]  21 580
[1]  21 578
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] "Skip p-value calculation to save time.  May help with Average-by-Site workflow, but generally not recommended."
[1] 21  5
[1] 21 10

[1] 21 10
[1] "unmethyl.cutoff > methyl.cutoff ..."
[1] "so, delta-beta decides which group should be subject to which cutoff"
[1]  0 10
[1]  2 10
[1]  2 10
[1]  2 10
Warning messages:
1: package ‘RColorBrewer’ was built under R version 4.1.3 
2: package ‘gplots’ was built under R version 4.1.3 
```

**Again, _please_ do not use any results like that in a publication.** 

The current goal is to just focus in making sure there is not a technical problem with the code (and/or file formatting issues, etc.)

The changes are very small, so I am surprised that more are also not identified.  However, you need some sites within the data frame for `filtered.sites` in order to proceed to next steps.

Even if more sites had been identified, I was **not** planning on continuing to the island step, given that I am not necessarily assuming or expecting the truncated data contains a CpG Island that is truly differentially methylated (even if that is in fact possible).

I have uploaded a **.zip file** with the exact files used for what I showed above (based upon what you [provided on sourceforge](https://sourceforge.net/p/cohcap/discussion/bioconductor/thread/3aa354ec/)):

[troubleshooting_example-230615.zip](https://github.com/cwarden45/COHCAP/files/11761080/troubleshooting_example-230615.zip)

**Third**, it goes beyond what I can help with through this medium, and I think it sounds like a match for what you should be able to do for troubleshooting on your own.  However, if there really aren't robust tumor versus normal changes being found, then I might take a step back and try to assess general trends in the data.  For example, I don't know if QC plots from _RnBeads_ might be helpful.  I would be surprised if it would make a huge difference - however, if you have access to raw data, you could try different normalizations in _minfi_.  COHCAP can handle multivariate analysis, but I am not immediately sure if that will be a great fit for your project.  Nevertheless, that does make me wonder about what might happen if you look at **percent tumor** as a continuous value (as a primary variable, which might even be more appropriate than trying to add that as a confounding 2nd variable).  If you have **paired tumor-normal sample**s with a much smaller sample size, then multivariate analysis would then be appropriate (and perhaps important).

I hope that this helps.

Best Wishes,
Charles

**Comment by Dilraj-kaur** [comment]
Hi Charles,
Thank you for your response. I finally managed to get some filtered CpG sites and 2 CpG islands with my complete datasets:

filtered.sites = COHCAP.site(sample.file, beta.table, project.name,
        project.folder, ref="Solid_Tissue_Normal",
        methyl.cutoff=0, unmethyl.cutoff=1,
        delta.beta.cutoff=0.01,pvalue.cutoff=1, fdr.cutoff=1)

island.list <- COHCAP.avg.by.island(sample.file, filtered.sites, beta.table, project.name, project.folder,
                                    ref="Solid_Tissue_Normal", methyl.cutoff=0, unmethyl.cutoff=1, delta.beta.cutoff=0.01, pvalue.cutoff=0.05)

[1] "Reading Sample Description File...."
[1] 374979    580
[1] 374979    578
[1] "Group: Primary_Tumor"       "Group: Solid_Tissue_Normal"
[1] "Checking CpG Site Stats Table"
[1] 131517     10
[1] 80350    10
[1] 21516
[1] "Average CpG Sites per CpG Island"
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 5390    8
[1] "unmethyl.cutoff > methyl.cutoff ..."
[1] "so, delta-beta decides which group should be subject to which cutoff"
[1] 2 8
[1] "There are 2 differentially methylated islands"
[1] 5390  580
[1]   2 580
[1] "Plotting Significant Islands Box-Plots.."
[1] 131518    581


I have a query thpugh how to change parameters like what is basis of these parameters. I believe its based on the distribution of beta values among the samples for entire file.
I tried to find a way to do some explorary data analysis (distribution plot, PCA, clustering, svd) with my data so that i can decide the paramters better. Can you suggets any package or way to do this speciafically with beta valued matrix and not the i.dat files.

PS: I dont have .Idat files, i have only beta valued matrix downaloded from TCGA-HNSCC.


Thank you 
Dilraj Kaur

**Comment by cwarden45** [comment]
Hi Dilraj,

Thank you for following up.

If the parameters that you are using with the full dataset only identify 2 sites, then I **don't** think you want to run the same tumor versus normal comparison with this data.  _The parameters that you used should likely never be used in a publication._  That said, it looks like you didn't change `fdr.cutoff` at the island step (from the default of FDR < 0.05).  **For example, I am not sure what happens if you use `fdr.cutoff=0.25` for _both_ site and island identification?**

It has been a little while since I have been assigned to work on a DNA Methylation project.  While I have admittedly usually started from .idat files with newly generated data, I am not sure if the following possibilities might help:

**1)** The [RnBeads page](https://rnbeads.org/) describes starting with GEO data and "tab" data as an input.  I can't provide detailed support for using RnBeads, but maybe that could be an option and you could ask for support from that developer?

**2)** There is an **explicit warning** that there are limits in support that can be provided for "templates" that I have posted on GitHub.  However, there is a [template to use COHCAP with the newer EPIC array](https://github.com/cwarden45/DNAmethylation_templates/tree/master/EPIC_workflow).  Even though the QC functions were depreciated from the Bioconductor version, there is a `qc.R` script that can be run downstream of either _minfi_ or `GenomeStudio` processing from .idat files.

To be clear, I am calling that `qc.R` script a **template** precisely because it is common for me to need to modify the code itself for various projects.  In order for that to be useful for somebody else, that requires familiarity with R.  **So, if you find reading through the code challenging, then I apologize that may not be as helpful a solution.**

Similarly, there is also code to run some newer functions added to Bioconductor (_not_ described in the [Protocol Exchange posting](https://protocolexchange.researchsquare.com/article/nprot-2965/v1)) in the `run_COHCAP.R` template.  While I am not planning on adding any new functions or making modifications beyond what is required to keep the package in Bioconductor, it is fair to ask questions related to running more newly added features (such as additional options for the `ref` and `num.groups` parameters; or the previously defined `paired` parameter).  Parameters like `alt.pvalue` and `lower.cont.quantile` and `upper.cont.quantile` should probably be considered more advanced, and maybe even "beta" features in some circumstances (even if those are options for troubleshooting).  However, I apologize that I can't provide support in running the _full_ scripts provided in the "template."

That said, if you wanted to try running **percent tumor (continuous variable)** analysis and/or **multivariate tumor vs normal analysis (with a much smaller sample size)** in COHCAP, can you please open separate tickets for each question?  I hope that might help others in making it easier to find relevant information.

I hope that I am understanding the situation correctly.  If there is anything that I might not be understanding, then please let me know.  **Otherwise, do you think it is OK if I close this issue?**  It is possible that using all of the tumor and normal samples in a single-variable analysis in COHCAP is not a good solution for TCGA-HNSCC data.  I am not sure if certain batches might be throwing off the results (and something between the full sample size and only the paired samples may be helpful to use) - however, I apologize that I believe that is beyond what I can provide assistance with through this forum.

Best Wishes,
Charles

**Comment by Dilraj-kaur** [comment]
HI Charles
Thank you, for your assistance. I have tried Rnbeads, methyl kit, betaclust, and few others. It seems like for exploratory analysis they requires .idat files (which i am now trying to download using TCGAbiolinks).
qc.R in COHCAP also works with .Idat files.
Currently i am trying Champ with the beta valued array  i have hoping to get some posiitive results.

while trying wiith fdr.cutoff=0.25 for both CpG sites and island i obtained 👍 

[1] "Group: Primary_Tumor"       "Group: Solid_Tissue_Normal"
[1] "Checking CpG Site Stats Table"
[1] 610  10
[1] 327  10
[1] 270
[1] "Average CpG Sites per CpG Island"
[1] "Differential Methylation Stats for 2 Groups with Reference"
[1] 5 8
[1] "unmethyl.cutoff > methyl.cutoff ..."
[1] "so, delta-beta decides which group should be subject to which cutoff"
[1] 5 8
[1] "There are 5 differentially methylated islands"
[1]   5 580
[1]   5 580
[1] "Plotting Significant Islands Box-Plots.."
[1] 611 581

I hereby attaching the results, the problem i think its not giving us  a clear stratification.

I am happy to start new thread for the discussion.  May be you are right with the data nad the method. Anyway, i appreciate your time and help.
 


[HNSC-full_CpG_site_heatmap.pdf](https://github.com/cwarden45/COHCAP/files/11833162/HNSC-full_CpG_site_heatmap.pdf)
[HS3ST1_chr4_11430235_11431256.pdf](https://github.com/cwarden45/COHCAP/files/11833163/HS3ST1_chr4_11430235_11431256.pdf)
[ISOC2_chr19_55972697_55973442.pdf](https://github.com/cwarden45/COHCAP/files/11833164/ISOC2_chr19_55972697_55973442.pdf)
[PRKAR1B_chr7_592620_593058.pdf](https://github.com/cwarden45/COHCAP/files/11833165/PRKAR1B_chr7_592620_593058.pdf)
[SDCCAG8_chr1_243637639_243638142.pdf](https://github.com/cwarden45/COHCAP/files/11833166/SDCCAG8_chr1_243637639_243638142.pdf)
[TPM1_chr15_63340256_63341464.pdf](https://github.com/cwarden45/COHCAP/files/11833167/TPM1_chr15_63340256_63341464.pdf)
[HNSC-full_CpG_island_heatmap-Avg_by_Island.pdf](https://github.com/cwarden45/COHCAP/files/11833168/HNSC-full_CpG_island_heatmap-Avg_by_Island.pdf). 


Regards

Dilraj Kaur

**Comment by cwarden45** [comment]
Hi Dilraj,

No matter what, I think additional work is needed before presenting results in a publication.

However, roughly speaking, I think using `fdr.cutoff=0.25` at _both_ steps may be preferable over using `fdr.cutoff=1.00` at the CpG Site step and `fdr.cutoff=0.05` (the default) at the CpG Island step.  Nevertheless, modifying thresholds at both steps is a general troubleshooting strategy.

If you have any additional questions and/or I might have misunderstood anything, then please let me know.  Otherwise, I am closing this particular ticket.

Yes - if you have questions related to continuous variable analysis or paired/multi-variate analysis, then I am happy to do what I can in separate "issues."

Thank you very much!

Sincerely,
Charles
